[tool.nixpacks]
providers = ["python"]

[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "python312Packages.virtualenv", "postgresql"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = ["chmod +x start.sh"]

[start]
cmd = ". /opt/venv/bin/activate && ./start.sh"
