[tool.nixpacks]
providers = ["python"]

[phases.setup]
nixPkgs = ["python312", "postgresql"]

[phases.install]
cmds = ["python3 -m pip install --upgrade pip", "python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = ["python3 manage.py collectstatic --noinput"]

[start]
cmd = "python3 manage.py migrate && gunicorn backend.wsgi --bind 0.0.0.0:$PORT"
